platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'WZPullRefresh_Example' do
  pod 'WZPullRefresh', :path => '../'

  target 'WZPullRefresh_Tests' do
    inherit! :search_paths
  end
end
